#! /usr/bin/perl

#Requires a unique ID (UUID) for grouping the data 
### $ ./matched_ratio 1174aa8b-4f1b-497a-bf16-3550f8964da7 
### $
### On successful completion returns 0. 
### Unuscessful completion reports to stdout and returns other code. 

#Return Codes:
# 1 = wrong parameters.
# 2 = couldn't perform operation on controller
# 3 = inconssitent information between queries
# 4 = Error with DB insert 

use REST::Client;
use JSON;
use MIME::Base64;
use DBI;

my $debug = 0;


#Print usage
sub help_text
{
	my $text = <<ENDTEXT;
Usage:$0 [-h|--help|--h] <Group_ID>
	-h 
		Prints this message, the program help.
	Group_ID
		A unique ID (UUID) for grouping the measurements.
ENDTEXT
	return $text;	
}

sub feature_name
{
	return "matched_percentage";
}

my $controller_ip;
my $onos_user;
my $onos_password;

my $db_ip;
my $db_name;
my $db_user;
my $db_pass;

my $group_id;

##These are constants... maybe I should've capitalized... but, whatever
my $port_statistics_uri; 
my $flow_statistics_uri;

sub setup
{
	if (scalar(@_) != 1)
	{
		print("Error! The transaction's group id (UUID) must be supplied!\n");
		print(help_text());
		exit(1);
	}

	($group_id) = @_;

	$controller_ip = (exists($ENV{'CONTROLLER_IP'}))?$ENV{'CONTROLLER_IP'}:"localhost";
	$onos_user = (exists($ENV{'ONOS_USER'}))?$ENV{'ONOS_USER'}:"onos";
	$onos_pass = (exists($ENV{'ONOS_PASS'}))?$ENV{'ONOS_PASS'}:"rocks";

	$db_ip = (exists($ENV{'DB_IP'}))?$ENV{'DB_IP'}:"localhost";
	$db_name = (exists($ENV{'DB_NAME'}))?$ENV{'DB_NAME'}:"qoe_db";
	$db_user = (exists($ENV{'DB_USER'}))?$ENV{'DB_USER'}:"qoe_user";
	$db_pass = (exists($ENV{'DB_PASS'}))?$ENV{'DB_PASS'}:"MPCLGP5432!";

	##These are constants... maybe I should've capitalized... but, whatever
	my $base_request_uri = "http://$controller_ip:8181/onos/v1";
	$port_statistics_uri = $base_request_uri . "/statistics/delta/ports";
	$flow_statistics_uri = $base_request_uri . "/statistics/flows/tables";

	if ($debug)
	{
		print ("Controller IP=".$controller_ip."\n");
		print ("Onos User=".$onos_user."\n");
		print ("Onos Password=".$onos_pass."\n");
		print ("Onos auth = ".encode_base64($onos_user.":".$onos_pass));

		print ("DN IP=".$db_ip."\n");
		print ("DB Name=".$db_name."\n");
		print ("DB User=".$db_user."\n");
		print ("DB Pass=".$db_pass."\n");

		print ("Group ID=".$group_id."\n");

	}	

}


sub insert_DB 
{
	if (scalar(@_) != 1)
	{
		print("Insert DB functino called without a value to insert!\n");
		exit(3);
	}

	(my $ratio) = @_;

	my $query = "INSERT INTO measure (datetime, parameter, value, groupid) VALUES (CURRENT_TIMESTAMP, '".feature_name()."', $ratio, '$group_id');";	
	my $connection = DBI->connect("DBI:Pg:dbname=$db_name;host=$db_ip", $db_user, $db_pass);
	my $statement = $connection->prepare($query);
	my $result = $statement->execute(); 
	if (!$result)
	{
		print $query."\n";
		print $statement->errstr."\n";
		exit (4);
	}
}

sub main
{


	if (scalar(@_) != 1)
	{
		print("Error! The transaction's group id (UUID) must be supplied!\n");
		print(help_text());
		exit(1);
	}
	
	setup(@_);

	my $client = REST::Client->new();

	#Start getting the matched packets
	$client->GET($flow_statistics_uri, {'Authorization' => "Basic ".encode_base64($onos_user.":".$onos_pass), 'Accept' => 'application/json'});
	if( !(($client->responseCode() eq '200') or ($client->responseCode() eq '201')))
	{
    		print "Error! Response Code ".$client->responseCode()."\n";
    		print "Response\n".$client->responseContent()."\n";
		exit (2);
	}

	my $flow_table_stats = from_json($client->responseContent());

	my $matchedPacketCounter = 0;
	my $lookedupPacketCounter = 0;
	my $avgMatchedRatio = 0;

	foreach (@{$flow_table_stats->{statistics}})
	{
		foreach (@{$_->{table}})
		{
			$matchedPacketCounter += $_->{packetsMatched};
			$lookedupPacketCounter += $_->{packetsLookedUp};
		}
	}

	$avgMatchedRatio = ($lookedupPacketCounter != 0)? $matchedPacketCounter / $lookedupPacketCounter * 100: 0;

	insert_DB ($avgMatchedRatio);	

}

main(@ARGV);

exit 0;
